services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    aintreallydown\EnergyBundle\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/EnergyBundle.php'